"""empty message

Revision ID: dd787ba1155e
Revises: bb7c582ef0f9
Create Date: 2024-12-21 21:50:51.767576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd787ba1155e'
down_revision = 'bb7c582ef0f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Text(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
